package: cloud.lazycat.app.codex-proxy-rs
version: 3.13.0
name: Codex Proxy RS
description: "面向 Codex 的自托管多账号 AI 网关"
min_os_version: "1.5.0"
homepage: https://github.com/zyycn/codex-proxy-rs
author: zyycn
license: Apache-2.0
permissions:
  required:
    - net.internet
locales:
  zh:
    name: Codex Proxy RS
    description: "面向 Codex 的自托管多账号 AI 网关"
  en:
    name: Codex Proxy RS
    description: "Self-hosted multi-account AI gateway for Codex"
